services:
  - type: web
    name: recipe-sharing-app
    env: node
    plan: free
    buildCommand: npm run install:all && npm run build:frontend
    startCommand: node backend/server.js
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false # Set this in Render Dashboard

